In [1]:
import pandas as pd

In [3]:
import sklearn.naive_bayes

In [22]:
#10 emails that have the phrase 'legitimate transaction'
l_emails = [1] * 10 + [0] * 2390

In [23]:
#list multiply by some number to replicate that list item
#9/10 of legit transaction is spam, 
spammy = [1] * 9 + [0] + [0] * 1799 + [1] * 591

In [24]:
df = pd.DataFrame(data={
        'contains_legitimate_transaction' : l_emails,
        'is_spam' : spammy
    })

In [25]:
df

contains_legitimate_transaction  is_spam
0                                   1        1
1                                   1        1
2                                   1        1
3                                   1        1
4                                   1        1
5                                   1        1
6                                   1        1
7                                   1        1
8                                   1        1
9                                   1        0
10                                  0        0
11                                  0        0
12                                  0        0
13                                  0        0
14                                  0        0
15                                  0        0
16                                  0        0
17                                  0        0
18                                  0        0
19                                  0        0
20                                  0        0
21                                  0        0
22                                  0        0
23                                  0        0
24                                  0        0
25                                  0        0
26                                  0        0
27                                  0        0
28                                  0        0
29                                  0        0
...                               ...      ...
2370                                0        1
2371                                0        1
2372                                0        1
2373                                0        1
2374                                0        1
2375                                0        1
2376                                0        1
2377                                0        1
2378                                0        1
2379                                0        1
2380                                0        1
2381                                0        1
2382                                0        1
2383                                0        1
2384                                0        1
2385                                0        1
2386                                0        1
2387                                0        1
2388                                0        1
2389                                0        1
2390                                0        1
2391                                0        1
2392                                0        1
2393                                0        1
2394                                0        1
2395                                0        1
2396                                0        1
2397                                0        1
2398                                0        1
2399                                0        1

[2400 rows x 2 columns]

In [26]:
classifier = sklearn.naive_bayes.GaussianNB()

In [27]:
classifier.fit(df[['contains_legitimate_transaction']], df.is_spam)

GaussianNB()

In [30]:
classifier.predict([1])

//anaconda/lib/python2.7/site-packages/sklearn/utils/validation.py:386: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and willraise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)


array([1])

In [31]:
#Was expecting 0.9?
classifier.predict_proba([1])

//anaconda/lib/python2.7/site-packages/sklearn/utils/validation.py:386: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and willraise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)


array([[ 0.,  1.]])

In [34]:
classifier.score(df[['contains_legitimate_transaction']], df.is_spam)

0.7533333333333333

In [35]:
df['unclaimed'] = [0] * 2399 + [1]

In [37]:
classifier.fit(df[['contains_legitimate_transaction', 'unclaimed']], df.is_spam)

GaussianNB()

In [38]:
classifier.predict([0,1])

//anaconda/lib/python2.7/site-packages/sklearn/utils/validation.py:386: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and willraise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)


array([1])

In [39]:
classifier.predict_proba([[0,1]])

array([[ 0.,  1.]])

In [40]:
df['the'] = 1 * 2400

In [43]:
classifier.fit(df[['contains_legitimate_transaction', 'unclaimed', 'the']], df.is_spam)

GaussianNB()

In [44]:
#does not contain unclaimed & legitimate transaction, but contains 'the
classifier.predict([[0,0,1]])

array([0])

In [46]:
classifier.predict([[0, 1, 1]])

array([1])

In [47]:
classifier.predict([[1, 0, 1]])

array([1])